// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Assets/_Scripts/proto/NetworkService.proto
// </auto-generated>
// Original file comments:
// packages\Grpc.Tools.1.11.0-pre2\tools\windows_x64\protoc.exe --csharp_out Assets\_Scripts\proto\genlibs --grpc_out Assets\_Scripts\proto\genlibs Assets\_Scripts\proto\NetworkService.proto --plugin=protoc-gen-grpc=packages\Grpc.Tools.1.11.0-pre2\tools\windows_x64\grpc_csharp_plugin.exe
//
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NetworkService {
  public static partial class NetworkService
  {
    static readonly string __ServiceName = "NetworkService.NetworkService";

    static readonly grpc::Marshaller<global::NetworkService.PingRequest> __Marshaller_PingRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetworkService.PingRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NetworkService.PingReply> __Marshaller_PingReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetworkService.PingReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NetworkService.JoinGameRequest> __Marshaller_JoinGameRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetworkService.JoinGameRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NetworkService.JoinGameReply> __Marshaller_JoinGameReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NetworkService.JoinGameReply.Parser.ParseFrom);

    static readonly grpc::Method<global::NetworkService.PingRequest, global::NetworkService.PingReply> __Method_PingService = new grpc::Method<global::NetworkService.PingRequest, global::NetworkService.PingReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PingService",
        __Marshaller_PingRequest,
        __Marshaller_PingReply);

    static readonly grpc::Method<global::NetworkService.JoinGameRequest, global::NetworkService.JoinGameReply> __Method_JoinGame = new grpc::Method<global::NetworkService.JoinGameRequest, global::NetworkService.JoinGameReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "JoinGame",
        __Marshaller_JoinGameRequest,
        __Marshaller_JoinGameReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NetworkService.NetworkServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NetworkService</summary>
    public abstract partial class NetworkServiceBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::NetworkService.PingReply> PingService(global::NetworkService.PingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Initiate joining a game
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::NetworkService.JoinGameReply> JoinGame(global::NetworkService.JoinGameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NetworkService</summary>
    public partial class NetworkServiceClient : grpc::ClientBase<NetworkServiceClient>
    {
      /// <summary>Creates a new client for NetworkService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NetworkServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NetworkService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NetworkServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NetworkServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NetworkServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::NetworkService.PingReply PingService(global::NetworkService.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingService(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::NetworkService.PingReply PingService(global::NetworkService.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PingService, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::NetworkService.PingReply> PingServiceAsync(global::NetworkService.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingServiceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::NetworkService.PingReply> PingServiceAsync(global::NetworkService.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PingService, null, options, request);
      }
      /// <summary>
      /// Initiate joining a game
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::NetworkService.JoinGameReply JoinGame(global::NetworkService.JoinGameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return JoinGame(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Initiate joining a game
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::NetworkService.JoinGameReply JoinGame(global::NetworkService.JoinGameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_JoinGame, null, options, request);
      }
      /// <summary>
      /// Initiate joining a game
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::NetworkService.JoinGameReply> JoinGameAsync(global::NetworkService.JoinGameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return JoinGameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Initiate joining a game
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::NetworkService.JoinGameReply> JoinGameAsync(global::NetworkService.JoinGameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_JoinGame, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NetworkServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NetworkServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(NetworkServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PingService, serviceImpl.PingService)
          .AddMethod(__Method_JoinGame, serviceImpl.JoinGame).Build();
    }

  }
}
#endregion
